# 错误处理

```ts
import axios,{ AxiosError } from 'axios'
axios.get('/test').catch(error: AxiosError){
  if(error.response){
    //请求正常发送 服务器响应了非 2xx
    console.log(error.response.data)
    console.log(error.response.status)
    console.log(error.response.headers)
  }else if(error.request){
    //请求正常发送 但服务没有响应
    console.log(error.request)
  }else{
    //其他未知的错误
    console.log('网络出现问题~')
  }
}
```